# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'compa' do
  pod 'AppCenter/Push', '~> 1.9.0'
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket'
    ]
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/Auth'
    pod 'react-native-maps', path: rn_maps_path
    pod 'GoogleMaps'  # Remove this line if you don't want to support Google Maps on iOS
    pod 'Google-Maps-iOS-Utils'
    pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support Google Maps on iOS
  platform :ios, '9.0'
    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'


    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
      end
      if target.name == "React"
        target.remove_from_project
      end
    end



  # Pods for gpsescolarpadres

  target 'compaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'compa-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gpsescolarpadres-tvOS

  target 'compa-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
